# Generated by Django 5.0 on 2023-12-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_alter_art_options_alter_art_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='category',
            field=models.ManyToManyField(to='blog.category', verbose_name='دسته بندی'),
        ),
    ]
